### PR TITLE
w1d3 code lab/homework

### PR DESCRIPTION
**Pull request by maggiemccain**
arrays and objects exercises.

### CODE REVIEW

**Comment by Kanairy** [comment]
hey Maggie,

you have a couple of files not inside the w1_d3 folder. Can you correct this and make another commit?

**Comment by maggiemccain** [comment]
cleaned up folder.  Not sure pull requesting this right....

**Comment by maggiemccain** [comment]
The pull request looked different to me this time around, but I think I’ve completed this.

**Comment by Kanairy** [comment]
looks good to me

**Pull request merged**
